### ISSUE TITLE
Support GARD Amory Object Detection Metrics

### ISSUE THREAD

**Issue by treubig26** [twosixlabs/armory-library#132]
Add support to use https://dbolya.github.io/tide/ for OD metrics.

**Comment by deprit** [comment]
Also include remaining GARD Armory object detection metrics:
- True positive rate,
- Misclassification rate,
- Disappearance rate,
- Hallucination rate.
These per image means are compute by the GARD Armory function `_object_detection_get_tpr_mr_dr_hr` in source `armory/metrics/task.py`.
