### ISSUE TITLE
document armory-library 

### ISSUE THREAD

**Issue by mwartell** [twosixlabs/armory-library#21]
- Reorg/rename/cleanup examples (just to make it easier to navigate & read)
- API documentation
   - Clean up docstrings, write/update usage docs
   - Publish to readthedocs?
- Conceptual documentation (most vague area in my mind)
    - History of armory?
    - Adversarial ML overview?
    - Armory as evaluation & analysis toolkit?
- Update top-levels #70  
- Organize examples #71
- Getting-started docs #72

---

- [ ] getting_started.md
- [ ] library_concepts.md
- [x] library_classes.md 
- [ ] dataset_creation.md # the RAITE dataset example

**Comment by mwartell** [comment]
Merged in #59 for API documentation

**Comment by deprit** [comment]
This issue has been broken into several smaller issues.
