### ISSUE TITLE
Rename benign/attack metrics to perturbed/unperturbed

### ISSUE THREAD

**Issue by treubig26** [twosixlabs/armory-library#31]
With the introduction of pre-computed adversarial datasets, it is misleading to have a "benign_" output metric that really represents an adversarial result.

If the output metrics are renamed to "unperturbed_" vs "perturbed_", it will be clearer that the inputs have or haven't been perturbed as part of that evaluation run.

Additionally, this sets the stage for future possibilities where the perturbation being made to the images is not always adversarial in nature.

**Comment by mwartell** [comment]
This may be obviated by #52
