### ISSUE TITLE
document bring-your-own-model import to Armory

### ISSUE THREAD

**Issue by mwartell** [twosixlabs/armory-library#35]
parallel to #30 but for models, perhaps Pokemon from earlier this year

**Comment by Honaker** [comment]
We decided to go with using a public model and weights from github.

**Comment by deprit** [comment]
Can we also consider the case of a model imported from an installed Python library?

**Comment by Honaker** [comment]
Yea I could do that as well. In the example notebook I could just show different ways of importing the model so from a library, github, and huggingface
