### ISSUE TITLE
Create Visualization for flowchart in armory

### ISSUE THREAD

**Issue by Honaker** [twosixlabs/armory-library#51]
Create a visualization flowchart for an armory user's example based on the flowchart below. The flowchart should be flipped vertically with the green arrows and boxes taken out. Beside the boxes for the image and attack boxes, the image can be shown and an example of the attack can be shown. The model box can show the metrics for the base model. The metrics box can display the metrics after the attack. This will allow users to easily create a visualization flowchart to show and explain armory-library to people more unfamiliar to the ml space. 

![image](https://github.com/twosixlabs/armory-library/assets/35696217/1e5766d5-512f-4ac9-8e0d-9922e18a3f8e)

**Comment by mwartell** [comment]
Step one should be an exploration of the likely technologies used to implement this and a markdown document explaining the broad approach.

- [ ] goals.md

**Comment by mwartell** [comment]
crudely flopped diagram for discussion
![image](https://github.com/twosixlabs/armory-library/assets/462695/2c54d341-976a-4843-b5a2-76cc96f21651)

**Comment by Honaker** [comment]
Second round of iteration version 
![image](https://github.com/twosixlabs/armory-library/assets/35696217/cf8a2609-ddb9-467a-8b7a-5a6caa2ef40d)
