### ISSUE TITLE
Support multiple perturbation chains in evaluation

### ISSUE THREAD

**Issue by treubig26** [twosixlabs/armory-library#52]
Currently, Armory supports two implicit inference actions during an evaluation run: benign and adversarial. That is, for each batch of the dataset, Armory performs a benign/unperturbed evaluation and then an adversarial/perturbed evaluation. The benign and attack evaluations can be individually enabled or disabled.

As the scope of Armory increases with regards to the types of perturbations that are executed against a model, as well as combinations (or chaining) of perturbations, it is clear that the current model isn't well suited to the comparative analysis we are aiming for with armory-library. That is, we want the user to be explicit about every perturbation chain (even the benign case) that will be performed by Armory during an evaluation. This allows for all the metrics for each perturbation chain to be exported to the same run in MLflow.

**Comment by deprit** [comment]
Since we are reviewing the Armory software architecture, this may be the moment to consider how poisoning attacks will fit into this perturbation and evaluation pipeline. Users would specify both clean data and some proportion of poisoned data used to train a model that is then evaluated.
