### ISSUE TITLE
Replace jatic-library with maite

### ISSUE THREAD

**Issue by treubig26** [twosixlabs/armory-library#58]
The JATIC-toolbox is being renamed to MAITE (Modular AI Trustworthy Engineering).

Our dev install script has a direct URL reference to their gitlab repository, which will need to be updated after they rename the repo.

We expect the package name to change, but it is unclear if there are any other API changes that will also impact armory.

**Comment by mwartell** [comment]
I think it is prudent to not move on this until MAITE is published to PyPI. I don't ever want a `git:` reference in our pyprojects if it can be avoided.

**Comment by treubig26** [comment]
> I think it is prudent to not move on this until MAITE is published to PyPI. I don't ever want a `git:` reference in our pyprojects if it can be avoided.

I forgot we never finished moving the git URL out of the `pyproject.toml` and into `dev-install.sh` (https://github.com/twosixlabs/armory-library/pull/47#discussion_r1392665086).

Either way, after they rename it, our scripts/project is broken. This will be very annoying if anyone is setting up a new venv.

**Comment by mwartell** [comment]
MAITE is now publicly released!
github: https://github.com/mit-ll-ai-technology/maite
pypi: https://pypi.org/project/maite/

**Comment by mwartell** [comment]
Overcome by events.
