### ISSUE TITLE
fix readthedocs build errors

### ISSUE THREAD

**Issue by mwartell** [twosixlabs/armory-library#74]
Branch `master` currently fails because:
```
python -m mkdocs build --clean --site-dir $READTHEDOCS_OUTPUT/html --config-file tools/mkdocs.yml
ERROR   -  Config value 'theme': Unrecognised theme name: 'material'. The available installed themes are: mkdocs, readthedocs
ERROR   -  Config value 'plugins': The "exclude" plugin is not installed
```

It likely needs a

    pip install mkdocs-material mkdocs-exclude

but it is not immediately obvious where to put them.

**Comment by treubig26** [comment]
I believe we need to add the additional package requirements to https://github.com/twosixlabs/armory-library/blob/master/.readthedocs.yaml (following https://docs.readthedocs.io/en/stable/config-file/v2.html#packages).
